name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest pytest-cov mypy ruff black isort
      - name: Lint
        run: |
          ruff check src
          black --check src tests
          isort --check-only src tests
      - name: Type check
        run: mypy src
      - name: Test
        run: pytest --cov=src --cov-report=xml
      - name: Build distributions
        if: matrix.python-version == '3.12'
        run: |
          pip install build
          python -m build
      - name: Upload artifacts
        if: matrix.python-version == '3.12'
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist
